import type { GeoPoint } from "../domain/types";
import { pathLengthKm } from "../domain/road-graph";
import { osmRoads, type OsmRoadSnapshotWay } from "../data/osm-roads";

// Real-road routing over a snapshot of the OpenStreetMap drivable network for
// the Mahadevapura pilot bbox (trunk/primary/secondary/tertiary/residential/
// living_street; oneways respected). The snapshot is generated by
// scripts/fetch-osm-roads.mjs and baked into the bundle, so routing works
// offline and never depends on Overpass at runtime. A* runs over these real
// street segments, so the blue route line and truck movement follow the same
// roads rendered on the OSM map tiles.

export type OverpassWay = {
  type: "way";
  id?: number;
  tags?: Record<string, string>;
  geometry?: { lat: number; lon: number }[];
};

type SnapshotWay = OsmRoadSnapshotWay;

export type RoadNetwork = {
  nodes: Map<string, GeoPoint>;
  edges: Map<string, { to: string; km: number }[]>;
  fetchedAt: string;
  wayCount: number;
};

// Pure great-circle km (no ×1.25 factor — real edges already are road length).
function sphereKm(a: GeoPoint, b: GeoPoint): number {
  const r = 6371; const rad = Math.PI / 180;
  const q = Math.sin(((b.lat - a.lat) * rad) / 2) ** 2 + Math.cos(a.lat * rad) * Math.cos(b.lat * rad) * Math.sin(((b.lng - a.lng) * rad) / 2) ** 2;
  return 2 * r * Math.asin(Math.sqrt(q));
}

const keyOf = (lat: number, lng: number) => `${lat.toFixed(6)},${lng.toFixed(6)}`;

function emptyNetwork(fetchedAt: string): RoadNetwork {
  return { nodes: new Map(), edges: new Map(), fetchedAt, wayCount: 0 };
}

function addSegment(network: RoadNetwork, a: GeoPoint, b: GeoPoint, oneWayForward: boolean, oneWayReverse: boolean) {
  const aKey = keyOf(a.lat, a.lng);
  const bKey = keyOf(b.lat, b.lng);
  const km = sphereKm(a, b);
  const forward = network.edges.get(aKey) ?? (network.edges.set(aKey, []), network.edges.get(aKey)!);
  const backward = network.edges.get(bKey) ?? (network.edges.set(bKey, []), network.edges.get(bKey)!);
  if (!oneWayReverse) forward.push({ to: bKey, km });
  if (!oneWayForward) backward.push({ to: aKey, km });
}

function appendWay(network: RoadNetwork, coords: number[], oneway: 0 | 1 | -1) {
  for (let i = 2; i < coords.length; i+=2) {
    const a = { lat: coords[i-2], lng: coords[i-1] };
    const b = { lat: coords[i], lng: coords[i+1] };
    network.nodes.set(keyOf(a.lat, a.lng), a);
    network.nodes.set(keyOf(b.lat, b.lng), b);
    addSegment(network, a, b, oneway === 1, oneway === -1);
  }
  network.wayCount++;
}

const DRIVABLE = /^(trunk|primary|secondary|tertiary|unclassified|residential|living_street)$/;

export function buildRoadNetwork(ways: OverpassWay[], fetchedAt = new Date().toISOString()): RoadNetwork {
  const network = emptyNetwork(fetchedAt);
  for (const way of ways) {
    const geometry = way.geometry ?? [];
    if (geometry.length < 2) continue;
    if (way.tags?.highway && !DRIVABLE.test(way.tags.highway)) continue;
    const oneway = way.tags?.oneway === "yes" || way.tags?.oneway === "1" ? 1 : way.tags?.oneway === "-1" ? -1 : 0;
    for (let i = 1; i < geometry.length; i++) {
      const a = { lat: geometry[i - 1].lat, lng: geometry[i - 1].lon };
      const b = { lat: geometry[i].lat, lng: geometry[i].lon };
      network.nodes.set(keyOf(a.lat, a.lng), a);
      network.nodes.set(keyOf(b.lat, b.lng), b);
      addSegment(network, a, b, oneway === 1, oneway === -1);
    }
    network.wayCount++;
  }
  return network;
}

type NetworkGlobal = typeof globalThis & { __wasteRoadNetwork?: RoadNetwork };

// Synchronous: the network is baked into the bundle, so building it is pure
// CPU work (cached on globalThis after the first call). Callers that `await`
// this still work — awaiting a non-Promise passes the value through.
export function getRoadNetwork(): RoadNetwork {
  const root = globalThis as NetworkGlobal;
  if (root.__wasteRoadNetwork) return root.__wasteRoadNetwork;
  const network = emptyNetwork(osmRoads.fetchedAt);
  for (const [, oneway, coords] of osmRoads.ways as SnapshotWay[]) appendWay(network, coords, oneway);
  root.__wasteRoadNetwork = network;
  return network;
}

export function nearestNode(network: RoadNetwork, point: GeoPoint): string | null {
  let bestKey: string | null = null;
  let best = Infinity;
  for (const [key, node] of network.nodes) {
    const d = (node.lat - point.lat) ** 2 + ((node.lng - point.lng) * Math.cos((node.lat * Math.PI) / 180)) ** 2;
    if (d < best) { best = d; bestKey = key; }
  }
  return bestKey;
}

function heuristicKm(network: RoadNetwork, key: string, goalKey: string): number {
  return sphereKm(network.nodes.get(key)!, network.nodes.get(goalKey)!);
}

// Binary min-heap keyed on f-score. A plain array scan is O(n) per expansion,
// which effectively hangs on the ~60k-node real OSM graph.
class MinHeap {
  private items: { key: string; f: number }[] = [];
  get size() { return this.items.length; }
  push(key: string, f: number) {
    const items = this.items;
    items.push({ key, f });
    let i = items.length - 1;
    while (i > 0) {
      const parent = (i - 1) >> 1;
      if (items[parent].f <= items[i].f) break;
      [items[parent], items[i]] = [items[i], items[parent]];
      i = parent;
    }
  }
  pop(): { key: string; f: number } | undefined {
    const items = this.items;
    if (items.length === 0) return undefined;
    const top = items[0];
    const last = items.pop()!;
    if (items.length > 0) {
      items[0] = last;
      let i = 0;
      for (;;) {
        const left = i * 2 + 1;
        const right = left + 1;
        let smallest = i;
        if (left < items.length && items[left].f < items[smallest].f) smallest = left;
        if (right < items.length && items[right].f < items[smallest].f) smallest = right;
        if (smallest === i) break;
        [items[smallest], items[i]] = [items[i], items[smallest]];
        i = smallest;
      }
    }
    return top;
  }
}

// Endpoints closer than this are joined directly instead of routed: snapping
// two nearby pins to opposite sides of a divider used to produce absurd loops
// (a 230 m hop becoming 2 km of driving).
const SHORT_LEG_KM = 0.35;

export function aStarOnNetwork(network: RoadNetwork, from: GeoPoint, to: GeoPoint): GeoPoint[] {
  if (sphereKm(from, to) <= SHORT_LEG_KM) return [from, to];
  const start = nearestNode(network, from);
  const goal = nearestNode(network, to);
  if (!start || !goal) return [from, to];
  if (start === goal) return [from, network.nodes.get(goal)!, to];

  const gScore = new Map<string, number>([[start, 0]]);
  const cameFrom = new Map<string, string>();
  const open = new MinHeap();
  open.push(start, heuristicKm(network, start, goal));

  while (open.size > 0) {
    const current = open.pop()!.key;
    if (current === goal) {
      const chain: string[] = [];
      let walk: string | undefined = current;
      while (walk && walk !== start) { chain.unshift(walk); walk = cameFrom.get(walk); }
      return [from, ...chain.map((key) => network.nodes.get(key)!), to];
    }
    const currentG = gScore.get(current) ?? Infinity;
    for (const edge of network.edges.get(current) ?? []) {
      const tentative = currentG + edge.km;
      if (tentative < (gScore.get(edge.to) ?? Infinity)) {
        cameFrom.set(edge.to, current);
        gScore.set(edge.to, tentative);
        open.push(edge.to, tentative + heuristicKm(network, edge.to, goal));
      }
    }
  }
  return [from, to]; // no connected path found
}

// Road trip through origin → stops → origin on real OSM streets. Distances use
// pure sphere km (real edge lengths), and distanceKm is the same cumulative
// metric as stopDistancesKm so progress math stays consistent.
export function realRoadTrip(network: RoadNetwork, points: GeoPoint[]): { path: GeoPoint[]; stopPoints: GeoPoint[]; stopDistancesKm: number[]; distanceKm: number } {
  const path: GeoPoint[] = points.length ? [points[0]] : [];
  for (let i = 1; i < points.length; i++) {
    const leg = aStarOnNetwork(network, points[i - 1], points[i]);
    for (const point of leg.slice(1)) {
      const last = path.at(-1);
      if (!last || last.lat.toFixed(6) !== point.lat.toFixed(6) || last.lng.toFixed(6) !== point.lng.toFixed(6)) path.push(point);
    }
  }
  const stopKeys = new Set(points.slice(1, -1).map((p) => `${p.lat.toFixed(6)},${p.lng.toFixed(6)}`));
  const stopDistancesKm: number[] = [];
  let cum = 0;
  const seen = new Set<string>();
  for (let i = 1; i < path.length; i++) {
    cum += sphereKm(path[i - 1], path[i]);
    const key = `${path[i].lat.toFixed(6)},${path[i].lng.toFixed(6)}`;
    if (stopKeys.has(key) && !seen.has(key)) { seen.add(key); stopDistancesKm.push(Number(cum.toFixed(3))); }
  }
  // Stops whose exact coordinate never shows up on the routed path (snapped
  // away by A*, or duplicated) still get a sane, increasing distance so the
  // map never highlights a leg at the wrong position.
  let lastDistance = stopDistancesKm.at(-1) ?? 0;
  while (stopDistancesKm.length < Math.max(0, points.length - 2)) {
    lastDistance = Math.min(cum * 0.98, lastDistance + Math.max(0.05, cum * 0.02));
    stopDistancesKm.push(Number(lastDistance.toFixed(3)));
  }
  for (let i = 1; i < stopDistancesKm.length; i++) {
    if (stopDistancesKm[i] <= stopDistancesKm[i - 1]) stopDistancesKm[i] = Number((stopDistancesKm[i - 1] + 0.01).toFixed(3));
  }
  return { path, stopPoints: points.slice(1, -1), stopDistancesKm, distanceKm: Number(cum.toFixed(3)) };
}

export { pathLengthKm };
