"use client";

import { useMemo, useRef, useState } from "react";
import { AlertTriangle, ArrowDownUp, Check, ChevronRight, CircleGauge, MapPinned, RadioTower, Route, Truck } from "lucide-react";
import { AppHeader } from "../../src/components/app-header";
import { BengaluruMap, type MapMarker } from "../../src/components/bengaluru-map";
import { PriorityAudit } from "../../src/components/priority-audit";
import { useDemo } from "../../src/components/demo-provider";
import { useRequireUser } from "../../src/components/auth";
import { uiCopy } from "../../src/data/copy";
import { MOCK_USER_LOCATION } from "../../src/components/bengaluru-map";
import { tripStatusFor } from "../../src/components/trip-status";

type Tab="overview"|"priority"|"routes"|"bins"|"placement";
const tabIds: Tab[]=["overview","priority","routes","bins","placement"];

export default function BbmpPage(){
 const {ready}=useRequireUser();
 const {state,locale,selectReport}=useDemo(); const copy=uiCopy[locale].bbmp; const [tab,setTab]=useState<Tab>("overview");
 const tabNav=useRef<HTMLElement>(null);
 const moveTab=(delta:number)=>{const nextTab=tabs[(tabs.findIndex(t=>t.id===tab)+delta+tabs.length)%tabs.length];setTab(nextTab.id);const buttons=tabNav.current?.querySelectorAll("button");(buttons?.[tabs.findIndex(t=>t.id===nextTab.id)] as HTMLButtonElement|undefined)?.focus()};
 const ranked=[...state.reports].filter(r=>!["confirmed"].includes(r.status)).sort((a,b)=>b.priority.audit.effectiveScore-a.priority.audit.effectiveScore);
 const selected=state.reports.find(r=>r.id===state.selectedReportId)??ranked[0];
 const markers=useMemo<MapMarker[]>(()=>[
   ...state.vehicles.map(v=>({id:v.id,label:v.label,location:v.location,kind:"vehicle" as const,detail:v.status.replaceAll("_"," ")})),
   ...state.bins.map(b=>({id:b.id,label:b.label,location:b.location,kind:"bin" as const,detail:`${Math.round(b.fillPercent)}% full`,overflow:b.fillPercent>=100})),
   ...state.reports.filter(r=>r.status!=="confirmed").map(r=>({id:r.id,label:r.title,location:r.location,kind:"report" as const,detail:`${r.priority.audit.effectiveScore.toFixed(1)} · ${r.priority.audit.effectiveBand}`})),
 ],[state]);
 const open=ranked.length, urgent=ranked.filter(r=>r.priority.audit.effectiveScore>=75).length, full=state.bins.filter(b=>b.fillPercent>=80).length;
 const tabs=useMemo(()=>tabIds.map(id=>({id,label:copy.tabs[id]})),[copy]);
 if(!ready) return <main className="app-shell"><AppHeader role="bbmp"/><div className="page-wrap"><p className="empty-state" role="status">Checking sign-in…</p></div></main>;
 return <main className="app-shell"><AppHeader role="bbmp"/><div className="ops-nav"><div><strong>{copy.navTitle}</strong><span>{copy.navSub}</span></div><nav aria-label="Operations sections" role="tablist" ref={tabNav} onKeyDown={e=>{if(e.key==="ArrowRight"){e.preventDefault();moveTab(1)}if(e.key==="ArrowLeft"){e.preventDefault();moveTab(-1)}}}>{tabs.map(item=><button role="tab" aria-selected={tab===item.id} tabIndex={tab===item.id?0:-1} key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}>{item.label}</button>)}</nav></div>
 <div className="page-wrap ops-wrap"><div className="live-banner"><RadioTower size={16}/><strong aria-live="polite">{state.lastAction}</strong><span aria-hidden="true">{copy.cursor} {state.events.at(-1)?.cursor} · {copy.seed} {state.seed}</span></div>
 {tab==="overview"&&<><section className="impact-strip" aria-label={copy.impact.title}>
  <ImpactStat label={`${copy.day.day} ${state.dayCycle.day} · ${state.dayCycle.phase==="en_route"?copy.day.collecting:state.dayCycle.phase==="servicing"?copy.day.servicing:copy.day.depot}`} value={state.dayCycle.phase==="at_depot"?`→ ${Math.floor(state.dayCycle.nextDepartureInMinutes/60)}h ${state.dayCycle.nextDepartureInMinutes%60}m`:`${state.dayCycle.binsServicedToday} ${copy.day.stopsToday}`}/>
  <ImpactStat label={copy.day.litresToday} value={`${state.dayCycle.litresCollectedToday} L`}/><ImpactStat label={copy.day.totalServiced} value={String(state.dayCycle.binsServicedTotal)}/><ImpactStat label={copy.day.overnight} value={state.dayCycle.phase==="at_depot"?copy.day.overnight:`${state.bins.filter(b=>b.fillPercent>=80).length} bins ≥80%`}/>
 </section>
 <section className="kpi-grid" aria-label="Live operations summary">
  <Kpi label={copy.kpis.open} value={open} detail={`${urgent} ${copy.kpis.urgent}`} icon={<AlertTriangle/>}/><Kpi label={copy.kpis.demand} value={state.signals.filter(s=>s.status!=="collected").length} detail={copy.kpis.waiting} icon={<RadioTower/>}/><Kpi label={copy.kpis.vehicles} value={state.vehicles.filter(v=>v.status==="en_route"||v.status==="collecting").length} detail={copy.kpis.ofTotal} icon={<Truck/>}/><Kpi label={copy.kpis.bins} value={full} detail={copy.kpis.threshold} icon={<CircleGauge/>}/>
 </section><section className="ops-grid"><article className="panel map-panel"><div className="section-heading split-heading"><div><p className="eyebrow">{copy.mapHeading}</p><h1>{copy.mapTitle}</h1></div><span className="source-chip">{copy.geography}</span></div><BengaluruMap markers={markers} route={state.route.roadPath} vehiclePaths={state.route.roadPathByVehicle} geometrySource={state.route.roadGeometrySource} tripStatus={tripStatusFor(state)} userLocation={MOCK_USER_LOCATION} height={530}/></article><PriorityQueue ranked={ranked} selectedId={selected?.id} onSelect={id=>{selectReport(id);setTab("priority")}}/></section></>}
 {tab==="priority"&&<section className="priority-layout"><PriorityQueue ranked={ranked} selectedId={selected?.id} onSelect={selectReport}/>{selected&&<PriorityAudit result={selected.priority}/>}</section>}
 {tab==="routes"&&<RoutesLab/>}
 {tab==="bins"&&<BinsTable/>}
 {tab==="placement"&&<PlacementLab/>}
 </div></main>;
}

function Kpi({label,value,detail,icon}:{label:string;value:number;detail:string;icon:React.ReactNode}){return <article className="kpi-card"><span>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>}

function ImpactStat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}

function PriorityQueue({ranked,selectedId,onSelect}:{ranked:ReturnType<typeof useDemo>["state"]["reports"];selectedId?:string;onSelect:(id:string)=>void}){const {locale}=useDemo();const copy=uiCopy[locale].bbmp;return <aside className="panel queue-panel"><div className="section-heading split-heading"><div><p className="eyebrow">{copy.queueEyebrow}</p><h2>{copy.queueTitle}</h2></div><ArrowDownUp size={18}/></div><div className="queue-list">{ranked.map((report,index)=><button key={report.id} className={selectedId===report.id?"queue-row selected":"queue-row"} onClick={()=>onSelect(report.id)}><span className="queue-rank">{String(index+1).padStart(2,"0")}</span><div><strong>{report.title}</strong><p>{report.locality} · {report.status}</p><small>{[...report.priority.audit.factors].sort((a,b)=>b.contribution-a.contribution).slice(0,2).map(f=>f.key.replace(/([A-Z])/g," $1").toLowerCase()).join(" + ")}</small></div><span className={`score-chip band-${report.priority.audit.effectiveBand}`}><b>{report.priority.audit.effectiveScore.toFixed(1)}</b>{report.priority.audit.effectiveBand}</span><ChevronRight/></button>)}</div></aside>}

function RoutesLab(){const {state,reoptimize,publishRoute}=useDemo();const trip=tripStatusFor(state);return <section><div className="lab-heading"><div><p className="eyebrow">multi-signal-aco-inspired-v1</p><h1>Adaptive route revision</h1><p>Five specialist colonies search the same feasible stop set. Active weights adapt to current urgency and every stop preserves its signal trail.</p></div><div><button data-testid="route-reoptimize" className="secondary-button" onClick={()=>reoptimize("manual_control_room")}>Recalculate</button><button data-testid="route-publish" className="primary-button" onClick={publishRoute}><Check size={18}/>Publish revision</button></div></div><div className="route-metrics"><div><span>Plan</span><strong>v{state.route.version} · {state.route.status}</strong></div><div><span>Distance</span><strong>{state.route.totalDistanceKm} km</strong></div><div><span>Duration</span><strong>{state.route.totalMinutes} min</strong></div><div><span>Unassigned</span><strong>{state.route.unassigned.length}</strong></div></div><section className="panel"><div className="section-heading"><p className="eyebrow">Adaptive signal weights</p><h2>What the optimizer is listening to</h2></div><div className="weights-grid">{Object.entries(state.route.weights).map(([key,value])=><div key={key}><span>{key.replace(/([A-Z])/g," $1")}</span><strong>{Math.round(value*100)}%</strong><i><b style={{width:`${value*100}%`}}/></i></div>)}</div></section><div className="route-columns">{state.route.routes.filter(r=>r.stops.length).map(route=><section className="panel" key={route.vehicleId}><div className="section-heading split-heading"><div><p className="eyebrow">{state.vehicles.find(v=>v.id===route.vehicleId)?.label}</p><h2>{route.stops.length} stops · {route.totalDistanceKm} km</h2></div><Route size={24}/></div><ol className="stop-list">{route.stops.map((stop,stopIndex)=><li key={stop.id}><span className="stop-sequence">{stop.sequence}</span><div className="stop-main"><div><strong>{stop.label}</strong><small>{stop.locality} · {trip&&trip.nextStopIndex!==null&&route.vehicleId===state.vehicles[0]?.id&&trip.nextStopIndex===stopIndex?(trip.servicing?"halting now":"ETA in "+trip.etaToNextMinutes+" min (live)"):"ETA "+stop.etaMinutes+" min"} · {stop.volumeLitres.toFixed(0)} L</small></div><span className={`status-chip status-${stop.status}`}>{stop.locked?"locked · ":""}{stop.status.replaceAll("_"," ")}</span><p>{stop.explanation}</p><div className="contribution-row">{stop.contributions.map(c=><span key={c.signal}><b>{c.contribution}</b>{c.label}</span>)}</div></div></li>)}</ol></section>)}</div>{state.route.unassigned.length>0&&<div className="alert warning"><AlertTriangle/><div><strong>Unassigned work</strong><p>{state.route.unassigned.map(x=>`${x.id}: ${x.reason}`).join(" · ")}</p></div></div>}</section>}

function BinsTable(){const {state}=useDemo();return <section className="panel"><div className="section-heading"><p className="eyebrow">Synthetic IoT telemetry</p><h1>Smart-bin status</h1></div><div className="table-scroll"><table className="data-table"><caption>Ten demo smart bins with deterministic fill telemetry</caption><thead><tr><th>Bin</th><th>Locality</th><th>Fill</th><th>Status</th><th>Streams</th><th>Freshness</th></tr></thead><tbody>{state.bins.map(bin=><tr key={bin.id}><th scope="row">{bin.label}</th><td>{bin.locality}</td><td><strong>{bin.fillPercent}%</strong></td><td><span className={`status-chip status-${bin.status}`}>{bin.status}</span></td><td>{bin.accepted.join(", ")}</td><td>{new Date(bin.lastUpdatedAt).toLocaleTimeString("en-IN")}</td></tr>)}</tbody></table></div></section>}

function PlacementLab(){const {state}=useDemo();const [selected,setSelected]=useState(state.recommendations[0]?.id);const rec=state.recommendations.find(r=>r.id===selected)??state.recommendations[0];const markers=state.recommendations.map(r=>({id:r.id,label:r.label,location:r.location,kind:"recommendation" as const,detail:`score ${r.score.toFixed(1)} · ${Math.round(r.confidence*100)}% confidence`}));return <section><div className="lab-heading"><div><p className="eyebrow">EPSG:32643 · 120 m grid · 300 m suppression</p><h1>Smart-bin placement lab</h1><p>Recommendations combine real Bengaluru geography proxies with labelled demo demand. Unknown land ownership always requires field validation.</p></div><span className="source-chip">OSM + official wards</span></div><div className="placement-layout"><div className="panel"><BengaluruMap markers={markers} height={500}/></div><aside className="panel placement-list"><div className="section-heading"><p className="eyebrow">Six diversified candidates</p><h2>Recommended public edges</h2></div>{state.recommendations.map(r=><button className={selected===r.id?"placement-row selected":"placement-row"} key={r.id} onClick={()=>setSelected(r.id)}><span>{r.rank}</span><div><strong>{r.label}</strong><small>{r.locality} · {Math.round(r.confidence*100)}% confidence</small></div><b>{r.score.toFixed(1)}</b></button>)}</aside></div>{rec&&<section className="panel recommendation-detail"><div className="section-heading split-heading"><div><p className="eyebrow">Recommendation #{rec.rank}</p><h2>{rec.label}</h2><p>{rec.reasons.join(" · ")}</p></div><div className="score-orb"><strong>{rec.score.toFixed(1)}</strong><span>placement</span></div></div>{rec.requiresFieldValidation&&<div className="alert warning"><MapPinned/><div><strong>Field validation required</strong><p>{rec.warnings.join(" ")}</p></div></div>}<div className="table-scroll"><table className="data-table"><caption>Complete placement score factor breakdown</caption><thead><tr><th>Factor</th><th>Raw</th><th>Normalized</th><th>Weight</th><th>Contribution</th><th>Source</th></tr></thead><tbody>{rec.features.map(f=><tr key={f.key}><th scope="row">{f.label}</th><td>{f.raw??"Unknown"}</td><td>{f.value.toFixed(2)}</td><td>{Math.round(f.weight*100)}%</td><td><strong>{f.contribution.toFixed(2)}</strong></td><td>{f.source.replaceAll("_"," ")}</td></tr>)}</tbody></table></div></section>}</section>}
