import { index, integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const json=<T>(name:string)=>text(name,{mode:"json"}).$type<T>();
const identity={id:text("id").primaryKey(),entityVersion:integer("entity_version").notNull().default(1),createdAt:text("created_at").notNull(),updatedAt:text("updated_at").notNull()};

export const vehicles=sqliteTable("vehicles",{...identity,label:text("label").notNull(),status:text("status").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),heading:real("heading").notNull(),capacityLitres:real("capacity_litres").notNull(),loadLitres:real("load_litres").notNull(),activeRouteId:text("active_route_id"),lastSeenAt:text("last_seen_at").notNull(),source:json<Record<string,unknown>>("source").notNull()},t=>[index("vehicle_status_idx").on(t.status),index("vehicle_seen_idx").on(t.lastSeenAt)]);
export const smartBins=sqliteTable("smart_bins",{...identity,label:text("label").notNull(),locality:text("locality").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),capacityLitres:real("capacity_litres").notNull(),fillPercent:real("fill_percent").notNull(),status:text("status").notNull(),acceptedStreams:json<string[]>("accepted_streams").notNull(),lastSensorAt:text("last_sensor_at").notNull(),source:json<Record<string,unknown>>("source").notNull()},t=>[index("bin_fill_idx").on(t.fillPercent),index("bin_status_idx").on(t.status)]);
export const wasteSignals=sqliteTable("waste_signals",{...identity,type:text("type").notNull(),category:text("category").notNull(),amountBand:text("amount_band").notNull(),locality:text("locality").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),status:text("status").notNull(),etaMinutes:integer("eta_minutes"),assignedVehicleId:text("assigned_vehicle_id"),source:json<Record<string,unknown>>("source").notNull()},t=>[index("signal_status_idx").on(t.status),index("signal_created_idx").on(t.createdAt)]);
export const reports=sqliteTable("garbage_reports",{...identity,title:text("title").notNull(),category:text("category").notNull(),locality:text("locality").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),status:text("status").notNull(),priorityScore:real("priority_score").notNull(),priorityBand:text("priority_band").notNull(),latestAuditId:text("latest_audit_id"),assignedVehicleId:text("assigned_vehicle_id"),photoAssetId:text("photo_asset_id"),source:json<Record<string,unknown>>("source").notNull()},t=>[index("report_rank_idx").on(t.status,t.priorityScore),index("report_created_idx").on(t.createdAt)]);
export const priorityAudits=sqliteTable("priority_audits",{id:text("id").primaryKey(),reportId:text("report_id").notNull(),version:text("version").notNull(),modelScore:real("model_score").notNull(),effectiveScore:real("effective_score").notNull(),modelBand:text("model_band").notNull(),effectiveBand:text("effective_band").notNull(),coverage:real("coverage").notNull(),missingFactors:json<string[]>("missing_factors").notNull(),manualReviewReasons:json<string[]>("manual_review_reasons").notNull(),safetyEscalation:json<Record<string,unknown>>("safety_escalation").notNull(),fullAudit:json<Record<string,unknown>>("full_audit").notNull(),calculatedAt:text("calculated_at").notNull()},t=>[index("audit_report_idx").on(t.reportId,t.calculatedAt),index("audit_score_idx").on(t.effectiveScore)]);
export const priorityFactors=sqliteTable("priority_factors",{id:text("id").primaryKey(),auditId:text("audit_id").notNull(),factorKey:text("factor_key").notNull(),present:integer("present",{mode:"boolean"}).notNull(),rawValue:json<unknown>("raw_value"),normalizedValue:real("normalized_value").notNull(),weight:real("weight").notNull(),contribution:real("contribution").notNull(),explanation:text("explanation").notNull()},t=>[uniqueIndex("audit_factor_unique").on(t.auditId,t.factorKey)]);
export const priorityOverrides=sqliteTable("priority_overrides",{id:text("id").primaryKey(),auditId:text("audit_id").notNull(),actor:text("actor").notNull(),reason:text("reason").notNull(),replacementScore:real("replacement_score"),replacementBand:text("replacement_band"),expiresAt:text("expires_at"),createdAt:text("created_at").notNull()},t=>[index("override_audit_idx").on(t.auditId)]);
export const routePlans=sqliteTable("route_plans",{...identity,status:text("status").notNull(),algorithm:text("algorithm").notNull(),seed:integer("seed").notNull(),trigger:text("trigger").notNull(),weights:json<Record<string,number>>("weights").notNull(),totalDistanceKm:real("total_distance_km").notNull(),totalMinutes:integer("total_minutes").notNull(),fallbackUsed:integer("fallback_used",{mode:"boolean"}).notNull(),distanceMode:text("distance_mode").notNull(),generatedAt:text("generated_at").notNull(),publishedAt:text("published_at")},t=>[index("route_status_idx").on(t.status,t.generatedAt)]);
export const routeStops=sqliteTable("route_stops",{...identity,routeId:text("route_id").notNull(),vehicleId:text("vehicle_id").notNull(),workId:text("work_id").notNull(),kind:text("kind").notNull(),sequence:integer("sequence").notNull(),status:text("status").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),volumeLitres:real("volume_litres").notNull(),explanation:json<Record<string,unknown>>("explanation").notNull(),locked:integer("locked",{mode:"boolean"}).notNull()},t=>[uniqueIndex("route_sequence_unique").on(t.routeId,t.vehicleId,t.sequence),index("route_work_idx").on(t.workId)]);
export const cleanupProofs=sqliteTable("cleanup_proofs",{...identity,reportId:text("report_id").notNull(),stopId:text("stop_id").notNull(),vehicleId:text("vehicle_id").notNull(),beforeAssetId:text("before_asset_id"),afterAssetId:text("after_asset_id"),gpsLat:real("gps_lat"),gpsLng:real("gps_lng"),checklist:json<Record<string,boolean>>("checklist").notNull(),status:text("status").notNull(),capturedAt:text("captured_at").notNull()},t=>[index("proof_report_idx").on(t.reportId),index("proof_stop_idx").on(t.stopId)]);
export const confirmations=sqliteTable("citizen_confirmations",{id:text("id").primaryKey(),reportId:text("report_id").notNull(),outcome:text("outcome").notNull(),note:text("note"),createdAt:text("created_at").notNull(),entityVersion:integer("entity_version").notNull().default(1)},t=>[index("confirmation_report_idx").on(t.reportId,t.createdAt)]);
export const placementRecommendations=sqliteTable("placement_recommendations",{...identity,rank:integer("rank").notNull(),label:text("label").notNull(),locality:text("locality").notNull(),lat:real("lat").notNull(),lng:real("lng").notNull(),score:real("score").notNull(),confidence:real("confidence").notNull(),factorAudit:json<Record<string,unknown>[]>("factor_audit").notNull(),constraints:json<string[]>("constraints").notNull(),warnings:json<string[]>("warnings").notNull(),provenance:json<Record<string,unknown>>("provenance").notNull()},t=>[index("placement_rank_idx").on(t.rank)]);
export const eventJournal=sqliteTable("event_journal",{cursor:integer("cursor").primaryKey({autoIncrement:true}),id:text("id").notNull(),topic:text("topic").notNull(),type:text("type").notNull(),entityType:text("entity_type").notNull(),entityId:text("entity_id").notNull(),entityVersion:integer("entity_version").notNull(),occurredAt:text("occurred_at").notNull(),payload:json<Record<string,unknown>>("payload").notNull()},t=>[uniqueIndex("event_id_unique").on(t.id),index("event_topic_cursor_idx").on(t.topic,t.cursor)]);
export const idempotencyKeys=sqliteTable("idempotency_keys",{key:text("key").primaryKey(),role:text("role").notNull(),route:text("route").notNull(),requestHash:text("request_hash").notNull(),responseStatus:integer("response_status").notNull(),responseBody:json<Record<string,unknown>>("response_body").notNull(),createdAt:text("created_at").notNull(),expiresAt:text("expires_at").notNull()},t=>[index("idempotency_expiry_idx").on(t.expiresAt)]);
export const simulationState=sqliteTable("simulation_state",{id:text("id").primaryKey(),seed:integer("seed").notNull(),tick:integer("tick").notNull(),now:text("now").notNull(),generation:integer("generation").notNull(),updatedAt:text("updated_at").notNull()});
