import { ArrowLeft, Database, Map, Route, ShieldCheck, Trash2 } from "lucide-react";
import Link from "next/link";
import { priorityConfig } from "../../src/domain/priority";

const sources = [
  { title: "Pilot boundary + population", body: "Current GBA 2025 Bengaluru East City Corporation, Mahadevapura Assembly wards 28–50. Official ward report total: 408,815 people across 23 wards.", href: "https://www.bbmp.gov.in/maps/", label: "Official corporation maps" },
  { title: "Roads, place names, POIs and exclusions", body: "OpenStreetMap supplies roads, localities, building-density proxies, water, rail and highway features. © OpenStreetMap contributors, ODbL 1.0.", href: "https://www.openstreetmap.org/copyright", label: "OpenStreetMap attribution" },
  { title: "Demographic context", body: "Historical context comes from Census of India PCA 2011. Current pilot counts use the official 2025 delimitation report.", href: "https://censusindia.gov.in/nada/index.php/catalog/6763/study-description", label: "Census India PCA" },
];

export default function AssumptionsPage() { return <main className="assumptions-page">
  <header><Link href="/"><ArrowLeft/>Back to role switch</Link><span className="demo-badge">Evidence + limits</span></header>
  <div className="assumptions-hero"><p className="eyebrow">Trust before spectacle</p><h1>Data, assumptions and algorithm cards.</h1><p>This independent prototype keeps real Bengaluru geography separate from clearly labelled synthetic operations. It supports GBA/BSWML-style coordination but has no official live government integration.</p><a className="landing-button landing-button-secondary" href="/impact-replay">Open deterministic impact replay</a></div>
  <div className="assumption-grid">{sources.map(source=><article className="assumption-card" key={source.title}><Map/><h2>{source.title}</h2><p>{source.body}</p><a href={source.href} target="_blank" rel="noreferrer">{source.label} ↗</a></article>)}</div>
  <section className="method-section"><div className="method-intro"><Database/><div><p className="eyebrow">Explainable priority-v1</p><h2>Ten observations. One additive result.</h2><p>Missing observations contribute zero, remain visible and reduce coverage. Coverage below 60% or missing safety fields requires manual review. Biomedical or chemical waste and traffic-lane blockage activate a separate floor of 90.</p></div></div><div className="table-scroll"><table className="data-table"><caption>Complete priority factor configuration</caption><thead><tr><th>Factor</th><th>Weight</th><th>Normalization</th></tr></thead><tbody>{priorityConfig.factorDefinitions.map(factor=><tr key={factor.key}><th scope="row">{factor.label}</th><td>{factor.weight}</td><td>{factor.normalization}</td></tr>)}</tbody></table></div></section>
  <section className="method-section route-method"><div className="method-intro"><Route/><div><p className="eyebrow">Route algorithm</p><h2>Five colonies, one feasible route.</h2></div></div><div className="assumption-grid compact-grid"><article><strong>Search</strong><p>18 iterations × 8 ants for each of smart-bin fill, citizen demand, report severity, urban density and travel efficiency. Seed 4242.</p></article><article><strong>Adaptation</strong><p>Base weights 24/22/24/15/15 respond to current urgency. Pheromone evaporates at 0.25; exploration is 0.08.</p></article><article><strong>Travel</strong><p>Bundled route geometry is preferred; the deterministic Haversine × 1.25 fallback at 20 km/h stays labelled.</p></article><article><strong>Guardrails</strong><p>Capacity and stop limits are enforced. Infeasible work remains visible with a reason; route explanations include all five signals.</p></article></div></section>
  <section className="method-section"><div className="method-intro"><Trash2/><div><p className="eyebrow">2026 source segregation + placement</p><h2>Four streams, suitable sites.</h2><p>Citizen guidance separates wet, dry, sanitary and special-care waste, while locality schedules remain explicitly unverified. Placement scores access and public-land suitability and excludes unsafe candidates.</p></div></div></section>
  <section className="privacy-card"><ShieldCheck/><div><h2>Privacy and demo authorization</h2><p>Operational telemetry, citizen actions, ETAs and cleanup evidence are deterministic synthetic data. Exact citizen locations belong only in role-guarded operational detail; public views use locality or coarsened cells. Demo role headers are a judge-friendly simulation—not production identity.</p></div></section>
</main>; }
